runtime: python310

handlers:
    - url: /(.*\.(?:js|ico|css|svg|png|jpg|gif))$
      static_files: \1
      upload: .*\.(?:js|ico|css|svg|png|jpg|gif)
      secure: always

    - url: /.*
      static_files: index.html
      secure: always
      upload: index.html
